name: Build and Push Docker Image

# This workflow runs on any push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a standard Linux version

    steps:
      # Check out code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/liatrio_app:${{ github.sha }}

      # Verify the application functionality
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master
